---
title: "final-evaluation-lindsey"
output: html_document
date: "2024-03-08"
---

# Assignment Info

- **Student name:** Lindsey King
- **Project title:** How Foreign Language Impacts Moral Decision Making
- **Submission date:** Mar 5 at 5:49pm

## Report plan summary

For my analysis, I plan to conduct an ANCOVA with the data to replicate what was done in the study I got the data from. For my figures, I will have two bar plots showing the consequentialism across dilemma categories in the three different language conditions. I will also include a scatterplot to visualize if there is any pattern between language proficiency in the foreign language and consequentialism % (this graph is looking like there isn't so I won't run an analysis on this). I will use the table to show demographic information of the breakdown across language categories. A decent chunk of words can be dedicated to the literature review as I can use sources for my own thesis that tie in as well as sources mentioned in the original study. The discussion will probably be the second largest section as it allows you to expand a bit more on things. Methods and Results will likely be smaller sections to keep things succinct. For in text references, I will likely reference the two bar plots as well as values that come from the ANCOVA. My personal goals for the final report are just to have a good grasp on the material to the point that I feel confident to go off and do this again with my own thesis data. The figure making and analysis conducting sections of class have been super informative and the practice homework in addition to applying the concepts to our reports has helped me get a better grasp. 

# Assessment

The lists of expectations in each category are to help you understand the kinds of things I'm looking for as I grade. These **do not** map onto point values. A checked box indicates the expectation was met or exceeded. (This also helps me spot patterns across students to identify ways I can improve the syllabus and lectures for future students.)

Ratings indicate overall success for each category and loosely map onto points. Starting from 20 points, no points are lost for the highest rating, -3 for the lowest, and somewhere in between for the middle ratings. Points lost in that range are dependent on how many issues there are, how much they matter, whether it's technicality vs problem of consequence, whether it's the same core issue that lost you points in a different section, whether exceeding expectations elsewhere compensate for a small issue, whether it's something we talked about in your report plan meeting, etc. 

Additional comments are included below the ratings as needed. Final project and class grades are included at the end of the document.

**WARNING: Grades for this assignment are going to be lower than you expect!** Don't freak out. I use "specs-based grading", which works very differently from the letter-grade-to-percentage conversion you are probably used to. It's more like Harry Potter OWLs -- 19/20 is outstanding, 16-18 exceeds expectations (not a C!), 13-15 meets expectations (not an F!), etc. You're not down to T(roll) until you're in the negatives. Remember this is only 20% of your final grade!

## .Rmd/PDF match

**Expectations:**

- [ ] PDF submitted to Canvas is identical to the PDF created when I knit your .Rmd
- [x] Knitting does not produce any errors or problematic warnings

**Rating:**

- [ ] Perfect match
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive error(s), missing PDF, or significant problems

Turn off your warnings/messages in setup chunks! Matches if I change those chunk options

## Data read-in, prep, wrangling

**Expectations:**

- [x] Data preparation and wrangling code present (may separate files)
- [x] Intermediate datasets (if used) are functional and read in successfully
- [x] Raw or intermediate data read into .Rmd code chunk
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Really nice and clean (and well-commented) source script

## Figures, tables, analyses

### Figures

**Expectations:**

- [x] At least 2 plots are produced in .Rmd chunks (not imported images)
- [x] Figures are different kinds of plots 
- [x] Figures follow report plan (may have inconsequential deviations)
- [ ] Figures are publication-quality
- [ ] Figures are sensibly captioned with `fig.cap` chunk option
- [x] Figures are informative and interpretable
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Really nice overall. To be truly "publication-quality" you need two changes: 1) adjust the axis ticks on the bar plots so they aren't using the literal factor values (e.g., instead of "footbridge.choice" use "Footbridge") and 2) a little more info in the captions (e.g., Figure 1 "Italian vs English" -> "Proportion of response type by language and dilemma")

### Table

**Expectations:** 

If you included more than the one required table, only one needs to meet expectations.

- [x] At least 1 table is produced in .Rmd chunk
- [x] Table follows report plan (may have inconsequential deviations)
- [x] Table is publication-quality
- [x] Table is sensibly captioned within the function (e.g., the kable caption argument)
- [x] Table is informative and interpretable
- [x] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Table 1 looks perfect! (and only 1 perfect table required) If you wanted to make Table 2 publication-quality, you'd need be sure all table text is in reader-friendly-APA-style format (e.g., "language.condition" -> "Language condition") and numbers are rounded to 3 decimal places

### Analysis

**Expectations:**

If you included more than the one required analysis (or other requirements agreed on in the report plan), only one needs to meet expectations.

- [x] At least 1 statistical analysis is executed in .Rmd chunk (or sourced code if appropriate)
- [x] Analysis follows report plan (may have inconsequential deviations)
- [x] Analysis is executed correctly
- [x] Analysis is appropriate (not necessarily ideal) for data type(s) and research questions
- [x] Analysis is referenced and interpreted in narrative text
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

*No additional comments*

## Manuscript

### Narrative text

**Expectations:**

- [x] Narrative text includes 1500+ words distributed across 4 sections
- [x] Sufficient literature review (per report plan)
- [x] Sufficient methods section (per report plan)
- [x] Sufficient results section (per report plan)
- [x] Sufficient discussion (per report plan)
- [x] Narrative provides sufficient context and interpretation for all figures, tables, and analyses
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

*No additional comments*

### Markdown

**Expectations:**

- [x] Figures and tables are successfully referenced with markdown syntax
- [x] At least 2 in-text code references
- [x] At least 1 in-text code reference includes in-text function
- [x] R Markdown is used effectively to follow APA format (e.g., headings, emphasized text)
- [ ] YAML header is functional and complete
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Really great use of in-text r code. You clearly get the point!! Would like to see you make better use of the papaja YAML, but that's not a major concern.

### BibTeX

**Expectations:**

- [x] At least 10 in-text citations using BibTeX reference syntax
- [x] In-text citations are rendered without errors
- [x] In-text citations have no obvious problems (e.g., incorrect special characters)
- [x] R and R packages are cited in-text using `cite_r()`
- [x] References page renders without errors
- [x] References page is APA formatted and free of obvious problems
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

*No additional comments*

## GitHub & best practices

These expectations will not have an impact on your grade unless there are egregious issues, but I include them to give you feedback on what you can do if you use this workflow going forward.

**Expectations:**

- [x] GitHub repo and contained files are sensibly and informatively named
- [x] GitHub repo is well-structured and tidy
- [x] GitHub README.md file is informative
- [x] Commit messages are informative
- [x] Style is (relatively) consistent
- [x] Comments are frequent and informative
- [x] Code chunks have informative names, follow 1-chunk-1-thing rule, and are distributed throughout the text

Commit messages both informative and entertaining (grading is boring and I hate DS_store ignore problems)

## Overall

Really excellent work, Lindsey! There are a few minor things you could clean up here and there, but overall you've done a great job putting everything we've covered this quarter into one cohesive and functional document.

# Grade

- **Final report grade:** 19
- **Class participation grade:** 19
- **Weekly assignments:** 60
- **TOTAL Final course grade:** 98 (A)
